@LanguageTranslator.WebAPI_HostAddress = https://localhost:7013

POST {{LanguageTranslator.WebAPI_HostAddress}}/languagetranslator/
Accept: application/json

GET {{LanguageTranslator.WebAPI_HostAddress}}/language/
Accept: application/json